project_name: nucleus
before:
  hooks:
    - go mod tidy # https://goreleaser.com/customization/builds/#go-modules
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

    binary: bin/nucleus

    ldflags:
      - -s -w -X 'github.com/nucleuscloud/cli/internal/version.buildDate={{.Date}}' -X 'github.com/nucleuscloud/cli/internal/version.gitCommit={{.Commit}}' -X 'github.com/nucleuscloud/cli/internal/version.gitVersion={{.Version}}'

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ incpatch .Version }}-next'
changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# brews:
#   - tap:
#       owner: nucleuscloud
#       name: homebrew-tap
#     folder: Formula
#     homepage: https://nucleuscloud.com
#     description: CLI for interfacing with Nucleus
#     license: MIT
signs:
  - artifacts: checksum
    # Used by GH Action to sign with a specific fingerprint
    args:
      [
        '--batch',
        '-u',
        '{{ .Env.GPG_FINGERPRINT }}',
        '--output',
        '${signature}',
        '--detach-sign',
        '${artifact}',
      ]
archives:
  -
    id: default
    format_overrides:
      - goos: windows
        format: zip
dockers:
  - image_templates:
    - nucleuscloud/cli
