name: Go

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        if: startsWith(github.ref, 'refs/tags/')

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.REPO_PAT }}:x-oauth-basic@github.com/haikuapp".insteadOf "https://github.com/haikuapp"

      - name: Build
        run: make build-ci

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/haiku_darwin_amd64
            bin/haiku_darwin_arm64
            bin/haiku_linux_386
            bin/haiku_linux_amd64
            bin/haiku_linux_arm64
            bin/haiku_windows_386
            bin/haiku_windows_amd64
