on:
  push:
    branches:
      - main
  pull_request:
name: Tests
jobs:
  test:
    name: run-tests
    strategy:
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.REPO_PAT }}:x-oauth-basic@github.com/nucleuscloud".insteadOf "https://github.com/nucleuscloud"
      - name: Test
        run: |
          go version
          go test -v ./...
