on:
  push:
    branches:
      - main
  pull_request:
name: Tests
jobs:
  test:
    name: run-tests
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.REPO_PAT }}:x-oauth-basic@github.com/nucleuscloud".insteadOf "https://github.com/nucleuscloud"

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: |
          go test -v ./...
